@ stdcall -import EmptyWorkingSet(long) 
@ stdcall -import EnumDeviceDrivers(ptr long ptr) 
@ stdcall -import EnumPageFilesA(ptr ptr) 
@ stdcall -import EnumPageFilesW(ptr ptr) 
@ stdcall -import EnumProcessModules(long ptr long ptr) 
@ stdcall -import EnumProcessModulesEx(long ptr long ptr long) 
@ stdcall -import EnumProcesses(ptr long ptr) 
@ stdcall -import GetDeviceDriverBaseNameA(ptr ptr long) 
@ stdcall -import GetDeviceDriverBaseNameW(ptr ptr long) 
@ stdcall -import GetDeviceDriverFileNameA(ptr ptr long) 
@ stdcall -import GetDeviceDriverFileNameW(ptr ptr long) 
@ stdcall -import GetMappedFileNameA(long ptr ptr long) 
@ stdcall -import GetMappedFileNameW(long ptr ptr long) 
@ stdcall -import GetModuleBaseNameA(long long ptr long) 
@ stdcall -import GetModuleBaseNameW(long long ptr long) 
@ stdcall -import GetModuleFileNameExA(long long ptr long) 
@ stdcall -import GetModuleFileNameExW(long long ptr long) 
@ stdcall -import GetModuleInformation(long long ptr long) 
@ stdcall -import GetPerformanceInfo(ptr long) 
@ stdcall -import GetProcessImageFileNameA(long ptr long) 
@ stdcall -import GetProcessImageFileNameW(long ptr long) 
@ stdcall -import GetProcessMemoryInfo(long ptr long) 
@ stdcall -import GetWsChanges(long ptr long) 
@ stdcall -import GetWsChangesEx(long ptr ptr) 
@ stdcall -import InitializeProcessForWsWatch(long) 
@ stdcall -import QueryWorkingSet(long ptr long) 
@ stdcall -import QueryWorkingSetEx(long ptr long) 
